import { Inter } from "next/font/google";
import "./globals.css";
import bg from '@/public/tictactoebg.png'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main style={{ backgroundImage: `url(${bg.src})` }} className=" text-center text-black font-bold bg-sky-500/50">
          <div className='bg-white bg-opacity-50 min-h-screen min-w-screen flex justify-center items-center relative'>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
